name: Django CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASS: ${{ secrets.MONGO_PASS }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Debug environment variables
        run: |
          echo "PostgreSQL Database: $POSTGRES_DB"
          echo "PostgreSQL User: $POSTGRES_USER"
          echo "MongoDB User: $MONGO_USER"

      - name: Start PostgreSQL
        run: |
          docker run -d \
            --name postgres \
            -e POSTGRES_DB=$POSTGRES_DB \
            -e POSTGRES_USER=$POSTGRES_USER \
            -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
            -p 5432:5432 \
            postgres:13

      - name: Wait for PostgreSQL to be ready
        run: |
          until PGPASSWORD=$POSTGRES_PASSWORD pg_isready -h localhost -p 5432 -U $POSTGRES_USER -d $POSTGRES_DB; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Start MongoDB
        run: |
          docker run -d \
            --name mongodb \
            -e MONGO_INITDB_ROOT_USERNAME=$MONGO_USER \
            -e MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS \
            -p 27017:27017 \
            mongo:latest
      
      - name: Install MongoDB Shell (mongosh)
        run: |
          curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/mongodb-server-keyring.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt update
          sudo apt install -y mongodb-mongosh


      - name: Wait for MongoDB to be ready
        run: |
          until mongosh --host localhost --port 27017 -u $MONGO_USER -p $MONGO_PASS --authenticationDatabase admin --eval 'db.adminCommand("ping")'; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
