name: Django CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASS: ${{ secrets.MONGO_PASS }}
      MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGO_USER }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGO_PASS }}

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U ${{ POSTGRES_USER }}" --health-timeout=30s --health-interval=5s --health-retries=3

      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" --health-timeout=30s --health-interval=5s --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Django environment
        run: |
          export DJANGO_SETTINGS_MODULE=autoML_final.settings
          export DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
          export MONGO_DB_URI=mongodb://$MONGO_USER:$MONGO_PASS@$MONGO_HOST:$MONGO_PORT/$MONGO_DB_NAME
          export MONGO_DB_NAME=$MONGO_DB_NAME
          export MONGO_USER=$MONGO_USER
          export MONGO_PASS=$MONGO_PASS
          export MONGO_HOST=$MONGO_HOST
          export MONGO_PORT=$MONGO_PORT
          export NAME_PG=$POSTGRES_DB
          export USER_PG=$POSTGRES_USER
          export PASSWORD_PG=$POSTGRES_PASSWORD
          export HOST_PG=$POSTGRES_HOST
          export PORT_PG=$POSTGRES_PORT

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U $POSTGRES_USER; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Install MongoDB Shell (mongosh)
        run: |
          curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/mongodb-server-keyring.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt update
          sudo apt install -y mongodb-mongosh

      - name: Wait for MongoDB to be ready
        run: |
          until mongosh --host localhost --port 27017 -u $MONGO_USER -p $MONGO_PASS --authenticationDatabase admin --eval 'db.adminCommand("ping")'; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
