name: Django CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASS: ${{ secrets.MONGO_PASS }}

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: >-
          --env POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          --env POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          --env POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          --health-cmd="pg_isready -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }}"
          --health-timeout=30s --health-interval=5s --health-retries=3

      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --env MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_USER }}
          --env MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_PASS }}
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-timeout=30s --health-interval=5s --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Debug environment variables
        run: |
          echo "POSTGRES_DB: $POSTGRES_DB"
          echo "POSTGRES_USER: $POSTGRES_USER"
          echo "MONGO_USER: $MONGO_USER"

      - name: Wait for PostgreSQL to be ready
        run: |
          until PGPASSWORD=$POSTGRES_PASSWORD pg_isready -h 127.0.0.1 -p 5432 -U $POSTGRES_USER -d $POSTGRES_DB; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Install MongoDB Shell (mongosh)
        run: |
          curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/mongodb-server-keyring.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt update
          sudo apt install -y mongodb-mongosh

      - name: Wait for MongoDB to be ready
        run: |
          until mongosh --host 127.0.0.1 --port 27017 -u $MONGO_USER -p $MONGO_PASS --authenticationDatabase admin --eval 'db.adminCommand("ping")'; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
