name: Django CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U ${{ secrets.POSTGRES_USER }}" --health-timeout=30s --health-interval=5s --health-retries=3
      
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASS }}
        options: --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" --health-timeout=30s --health-interval=5s --health-retries=3

    steps:
      # Checkout the code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.8'  # Choisis la version de Python que tu utilises dans ton projet

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Wait for the Postgres service to be ready
      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h ${{ secrets.POSTGRES_HOST }} -p ${{ secrets.POSTGRES_PORT }} -U ${{ secrets.POSTGRES_USER }}; do
            echo "Waiting for postgres..."
            sleep 2
          done

      # Wait for MongoDB to be ready
      - name: Wait for MongoDB to be ready
        run: |
          until mongosh --host ${{ secrets.MONGO_HOST }} --port ${{ secrets.MONGO_PORT }} --username ${{ secrets.MONGO_USER }} --password ${{ secrets.MONGO_PASS }} --eval 'db.adminCommand("ping")'; do
            echo "Waiting for MongoDB..."
            sleep 2
          done

      # Set up Django environment
      - name: Set up Django environment
        run: |
          export DJANGO_SETTINGS_MODULE=autoML_final.settings
          export DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
          export MONGO_DB_URI=mongodb://$MONGO_USER:$MONGO_PASS@$MONGO_HOST:$MONGO_PORT/$MONGO_DB_NAME
          export MONGO_DB_NAME=$MONGO_DB_NAME
          export MONGO_USER=$MONGO_USER
          export MONGO_PASS=$MONGO_PASS
          export MONGO_HOST=$MONGO_HOST
          export MONGO_PORT=$MONGO_PORT
          export NAME_PG=$POSTGRES_DB
          export USER_PG=$POSTGRES_USER
          export PASSWORD_PG=$POSTGRES_PASSWORD
          export HOST_PG=$POSTGRES_HOST
          export PORT_PG=$POSTGRES_PORT

      # Run migrations
      - name: Run migrations
        run: |
          python manage.py migrate

      # Run tests
      - name: Run tests
        run: |
          python manage.py test
