
name: Django CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testing_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U test_user" --health-timeout=30s --health-interval=5s --health-retries=3
      
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: mongo_test
          MONGO_INITDB_ROOT_PASSWORD: mongo_test
        options: --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" --health-timeout=30s --health-interval=5s --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> $GITHUB_ENV
          echo "MONGO_PASS=${{ secrets.MONGO_PASS }}" >> $GITHUB_ENV

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U $POSTGRES_USER; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Wait for MongoDB to be ready
        run: |
          until mongosh --host localhost --port 27017 --username $MONGO_USER --password $MONGO_PASS --eval 'db.adminCommand("ping")'; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
